aeternity/aeproject

README.md

Update the documentation to be more informational

Review documentation

---

forgae-cli.js
package-lock.json

Taking the cli version from the package.json and updating it automatically

Update cli version automatically

---

README.md
package-lock.json
package.json

Add info about localhost to documentation and fix npm information

Add localhost info

---

cli-commands/forgae-deploy/deploy.js
cli-commands/forgae-init/init.js
test/commands-tests/init.js

Update libraries like js-sdk and forgae when making` forgae init --update`

Libraries update

---

cli-commands/forgae-init/init.js

make forgae work on windows

---

cli-commands/forgae-init/artifacts/exampleTests.js
cli-commands/forgae-init/init.js
cli-commands/utils.js
package-lock.json
package.json

update sdk version. 

---

cli-commands/forgae-node/config.json
cli-commands/forgae-node/node.js
test/commands-tests/node.js

node should not start in every folder

---

cli-commands/forgae-init/init.js
cli-commands/forgae-node/config.json
cli-commands/forgae-node/node.js
package-lock.json
test/commands-tests/node.js

Merge latest changes from develop branch to master. Including travis changes and one bug fix

Merge develop branch into master 

---

cli-commands/forgae-compile/compile.js
cli-commands/forgae-init/artifacts/docker-compose.yml
cli-commands/forgae-init/artifacts/docker/epoch_node1_mean15.yaml
cli-commands/forgae-init/artifacts/docker/epoch_node2_mean15.yaml
cli-commands/forgae-init/artifacts/docker/epoch_node3_mean15.yaml

you should update your local docker image: "docker pull aeternity/aeternity"
closes #71

Update node version#71

---

README.md
cli-commands/commands.js
cli-commands/config.json
cli-commands/forgae-compile/compile.js
cli-commands/forgae-deploy/deploy.js
cli-commands/forgae-deploy/forgae-deployer.js
cli-commands/forgae-init/artifacts/deployTemplate.js
cli-commands/forgae-node/config.json
cli-commands/forgae-node/node.js
cli-commands/utils.js
test/commands-tests/compile.js
test/commands-tests/deploy.js
test/commands-tests/node.js
test/constants.json

add local compiler to 'node' command, subcmd 'only' to start ae node

---

packages/forgae-cli/forgae-compile/compile.js
packages/forgae-utils/utils/forgae-utils.js

fixed recursion,
set dependency as local object

fixed recursion

---

packages/aeproject-cli/aeproject-init/artifacts/ExampleContract.aes
packages/aeproject-cli/aeproject-init/artifacts/exampleTests.js

Test for the event will be implemented at later stage. Now it could not be deserialised

refactor smart contract

---

packages/aeproject-cli/aeproject-init/init.js
test/commands-tests/deploy.js

* Uninstall deprecated `forgae` dependencies (if any) while migrating a project from forgae to aeproject

added func to remove deprecated dependencies on aeproject init update

---

packages/aeproject-cli/aeproject-init/init.js

rearrange checks when uninstall forgae dependencies

---

packages/aeproject-cli/aeproject-env/EnvService.js

after updating docker-compose to >= 1.25, spawn result from `docker-compose ps` was a limit to 80 columns (characters) to row. `export COLUMN=xx && docker-compose ....` increase column(characters) per row. On windows, there is no such an issue but command-prompt do not understand/know command  `export VARIABLE=xxx`

[HOT-FIX] windows do not understand 'EXPORT' cmd

---

packages/aeproject-cli/package.json
packages/aeproject-config/package.json
packages/aeproject-lib/package.json
packages/aeproject-logger/package.json
packages/aeproject-utils/package.json

- aeproject@2.1.0
- aeproject-config@2.1.0
- aeproject-lib@2.1.0
- aeproject-logger@2.1.0
- aeproject-utils@2.1.0

Merge master after release 16.12.2019

---

doc/developer-documentation/aeproject-cli/contracts.md
doc/developer-documentation/aeproject-cli/fire-editor.md
packages/aeproject-cli/aeproject-contracts/aeproject-contracts.js
packages/aeproject-cli/aeproject-fire-editor/fire-editor.js
packages/aeproject-cli/commands.js
test/commands-tests/fire-editor-tests.js
test/constants.json

replace --ignoreOpenInBrowser with --ignorebrowser

simplify cli cmd option

---

packages/aeproject-cli/aeproject-init/init.js
packages/aeproject-utils/index.js
packages/aeproject-utils/utils/aeproject-utils.js

add '^' caret to package json dependency

add '^' caret to dependency

---

aeproject-cli/aeproject-compile/compile.js
aeproject-cli/aeproject-init/artifacts/docker/aeternity.yaml
package-lock.json
package.json
test/commands-tests/compile.js

- Activate Iris HF and FATE_2 by default #383 
- Print detailed messages for compilation errors #384

Release 3.0.5

---

docs/cli/test.md
docs/migration-from-3.x.x-to-4.x.x.md
src/init/update-artifacts/test/exampleTest.js
src/lib/utils.js

closes #402 
tests fail until https://github.com/aeternity/aeproject/issues/404 is resolved

chore: adapt to naming convention of sdk examples

---

docs/requirements.txt

should fix https://github.com/mkdocs/mkdocs/issues/2799

chore(deps): bump mkdocs version from 1.2.3 to 1.2.4

---

docs/cli/test.md
docs/lib.md
mkdocs.yml
src/lib/utils.js

docs: added docs for exposed aeproject lib

---

src/env/env.js

fix: consider env running check if any container is up

---

src/init/update-artifacts/docker-compose.yml

closes https://github.com/aeternity/aeproject/issues/431

feat: allow usage of native docker-compose without specifying env

---

src/lib/utils.js

fix: correct escaping to use - in filesystem contracts

---

src/env/env.js

feat: add image versions in env --info

---

src/config/node-config.json
src/init/update-artifacts/docker-compose.yml

https://github.com/aeternity/aeproject/pull/447#discussion_r1038023101

fix: use specific version of node to fix tests

---

docs/requirements.txt

nothing urgent. but as I updated again in protocol repo I thought it is good to update everywhere

chore(deps): mkdocs version update

---

docs/cli/env.md
docs/cli/test.md
src/init/constants.json
src/init/update-artifacts/test/exampleTest.js

fix: minor fixes, adjust docs
